// Шрифты редактора (набор как на evyt.ru). Файлы лежат в public/fonts,
// подключаются лениво через @font-face (injectFonts) — качаются при первом использовании.
export const EDITOR_FONTS: { family: string; url: string }[] = [
  { family: "Alina", url: "/fonts/Alina.ttf" },
  { family: "Alora", url: "/fonts/Alora.ttf" },
  { family: "Amelia", url: "/fonts/Amelia.ttf" },
  { family: "Anna", url: "/fonts/Anna.ttf" },
  { family: "Arianna", url: "/fonts/Arianna.ttf" },
  { family: "Aspen", url: "/fonts/Aspen.ttf" },
  { family: "Avery", url: "/fonts/Avery.ttf" },
  { family: "Betmo", url: "/fonts/Betmo.ttf" },
  { family: "Blair", url: "/fonts/Blair.ttf" },
  { family: "Brielle", url: "/fonts/Brielle.ttf" },
  { family: "Callie", url: "/fonts/Callie.ttf" },
  { family: "Carmen", url: "/fonts/Carmen.ttf" },
  { family: "Catarina", url: "/fonts/Catarina.ttf" },
  { family: "Collins", url: "/fonts/Collins.ttf" },
  { family: "Dakota", url: "/fonts/Dakota.ttf" },
  { family: "Dora", url: "/fonts/Dora.ttf" },
  { family: "Eleonora", url: "/fonts/Eleonora.ttf" },
  { family: "Elise", url: "/fonts/Elise.ttf" },
  { family: "Elsa", url: "/fonts/Elsa.ttf" },
  { family: "Emma", url: "/fonts/Emma.ttf" },
  { family: "Evelyn", url: "/fonts/Evelyn.ttf" },
  { family: "Fiona", url: "/fonts/Fiona.ttf" },
  { family: "Flora", url: "/fonts/Flora.ttf" },
  { family: "Flora Bold", url: "/fonts/Flora_Bold.ttf" },
  { family: "Grace", url: "/fonts/Grace.ttf" },
  { family: "Hadley", url: "/fonts/Hadley.ttf" },
  { family: "Harmony", url: "/fonts/Harmony.ttf" },
  { family: "Hope", url: "/fonts/Hope.ttf" },
  { family: "Isabelle", url: "/fonts/Isabelle.ttf" },
  { family: "Ivy", url: "/fonts/Ivy.ttf" },
  { family: "Jolly", url: "/fonts/Jolly.ttf" },
  { family: "Josie", url: "/fonts/Josie.ttf" },
  { family: "Journee", url: "/fonts/Journee.ttf" },
  { family: "Juniper", url: "/fonts/Juniper.ttf" },
  { family: "Kailani", url: "/fonts/Kailani.ttf" },
  { family: "Kendall", url: "/fonts/Kendall.ttf" },
  { family: "Khloe", url: "/fonts/Khloe.ttf" },
  { family: "Lilah", url: "/fonts/Lilah.ttf" },
  { family: "Literata", url: "/fonts/Literata.ttf" },
  { family: "Lora", url: "/fonts/Lora.ttf" },
  { family: "Lucille", url: "/fonts/Lucille.ttf" },
  { family: "Luna", url: "/fonts/Luna.ttf" },
  { family: "Maeve", url: "/fonts/Maeve.ttf" },
  { family: "Mckenna", url: "/fonts/Mckenna.ttf" },
  { family: "Megan", url: "/fonts/Megan.ttf" },
  { family: "Melody", url: "/fonts/Melody.ttf" },
  { family: "Milani", url: "/fonts/Milani.ttf" },
  { family: "Millie", url: "/fonts/Millie.ttf" },
  { family: "Nicoletta", url: "/fonts/Nicoletta.ttf" },
  { family: "Noelle", url: "/fonts/Noelle.ttf" },
  { family: "Nova", url: "/fonts/Nova.ttf" },
  { family: "Oks", url: "/fonts/Oks.ttf" },
  { family: "Olive", url: "/fonts/Olive.ttf" },
  { family: "Olivia", url: "/fonts/Olivia.ttf" },
  { family: "Paisley", url: "/fonts/Paisley.ttf" },
  { family: "Palmer", url: "/fonts/Palmer.ttf" },
  { family: "Phoebe", url: "/fonts/Phoebe.ttf" },
  { family: "Playfair", url: "/fonts/Playfair.ttf" },
  { family: "Prata", url: "/fonts/Prata.ttf" },
  { family: "River", url: "/fonts/River.ttf" },
  { family: "Roboto", url: "/fonts/Roboto.ttf" },
  { family: "Roboto Bold", url: "/fonts/Roboto_Bold.ttf" },
  { family: "Rowan", url: "/fonts/Rowan.ttf" },
  { family: "Ruby", url: "/fonts/Ruby.ttf" },
  { family: "Selena", url: "/fonts/Selena.ttf" },
  { family: "Skylar", url: "/fonts/Skylar.ttf" },
  { family: "Sloane", url: "/fonts/Sloane.ttf" },
  { family: "Sophia", url: "/fonts/Sophia.ttf" },
  { family: "Stella", url: "/fonts/Stella.ttf" },
  { family: "Sunny", url: "/fonts/Sunny.ttf" },
  { family: "Sutton", url: "/fonts/Sutton.ttf" },
  { family: "Talia", url: "/fonts/Talia.ttf" },
  { family: "Tatum", url: "/fonts/Tatum.ttf" },
  { family: "Tessa", url: "/fonts/Tessa.ttf" },
  { family: "Tessa Bold", url: "/fonts/Tessa_Bold.ttf" },
  { family: "Thea", url: "/fonts/Thea.ttf" },
  { family: "Thea Bold", url: "/fonts/Thea_Bold.ttf" },
  { family: "Vetrino", url: "/fonts/Vetrino.ttf" },
  { family: "Victoria", url: "/fonts/Victoria.ttf" },
  { family: "Violet", url: "/fonts/Violet.ttf" },
  { family: "Yeast", url: "/fonts/Yeast.ttf" },
];
